default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASS"] %>
  host: <%= ENV["DB_HOST"] %>

development:
  <<: *default
  database: controladmin_development

test:
  <<: *default
  database: controladmin_test
  
production:
  <<: *default
  database: <%= ENV["DB_NAME"]%>